Первое ДЗ
shaste/fake-burrberry-frontend pull request #1
Opened 2017-08-02 17:24 UTC by shaste

2017-08-02 22:03 UTC, evgenyrodionov commented
Переключи внимание с курса на продукт — не первое дз, а что конкретно ты сделал для продукта

2017-08-02 22:13 UTC, evgenyrodionov commented
https://rawgit.com/shaste/fake-burrberry-frontend/feat/product-page/product-page.html

шрифты слишком жирные

и тут мыльцо
![image](https://user-images.githubusercontent.com/775692/28897349-fb8a696c-77e8-11e7-9581-4a56d4e7e15d.png)

2017-08-02 22:16 UTC, imevro requested changes

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +        <img class="product-photos-elem" src="img/Long-Cotton-Gabardine Car-Coat-1@2x.jpg" alt="Front view">
elem? плохой неочевидный нейминг

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +          <p class="product-details-content-vendor_code">
почему-стиль-так_скачет?

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +          <img class="product-description-button-icon" src="img/triangle.svg">
в цсс

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +            A refined car coat crafted in protective cotton gabardine.<br>
это параграфы

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +            Outer: 100% cotton<br>
это списки

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +        <h2 class="h2 product-recommends-title">We recommend</h2>
h2 классом? нахуя?

2017-08-02 22:16 UTC, evgenyrodionov commented on product-page.html
> +          <div class="product-recommends-card-one">
что такое product-recommends-card-one?

2017-08-02 22:16 UTC, evgenyrodionov commented on css/product-page.css
> +    overflow: -moz-scrollbars-none;
вот не надо этого

2017-08-04 09:01 UTC, imevro requested changes
- кодстайл в цсс
- стили на тегах

2017-08-04 09:01 UTC, evgenyrodionov commented on css/product-page.css
> +  font-family: "Raleway", "Helvetica Neue", sans-serif;
если не будет гельветики нью? что тогда?

2017-08-04 09:01 UTC, evgenyrodionov commented on css/product-page.css
> +  margin: 0;
перестань резетить марджины

2017-08-04 09:01 UTC, evgenyrodionov commented on css/product-page.css
> +.a {
это что за класс?

2017-08-04 13:39 UTC, imevro requested changes

2017-08-04 13:39 UTC, evgenyrodionov commented on css/product-page.css
> +ul {
Сброс дефолтных стилей — плохо

2017-08-04 13:39 UTC, evgenyrodionov commented on product-page.html
> +        <button class="footer-btn" type="submit" name="choose-shipping-country">Shipping country: Russian Federation</button>
почему сабмит?

2017-08-04 18:00 UTC, imevro requested changes

2017-08-04 18:00 UTC, evgenyrodionov commented on product-page.html
> +        <div class="product-photo-gallery-item">
зачем ты добавил лишние дивы

2017-08-04 21:06 UTC, imevro approved these changes

2017-08-05 12:56 UTC, shaste commented
мылится в блоке Delivery  потому что в макете у заголовка Description line-height 20 px, a у заголовка Delivery — 19. чтобы было единство в стилях, я не стал это корректировать

2017-08-05 14:59 UTC, evgenyrodionov commented
Красавчик

2017-08-05 15:35 UTC, evgenyrodionov commented
![image](https://user-images.githubusercontent.com/775692/28996617-d9055368-7a0c-11e7-9bae-c94cab3e6c71.png)

2017-08-05 15:36 UTC, imevro requested changes

2017-08-05 15:36 UTC, evgenyrodionov commented on product-page.html
> +          <div class="col-xs-12 col-sm-12 col-md-5">
можно опустить sm-12 — будет 12 колонок до md-5, потому что ты на xs объявил

2017-08-05 15:36 UTC, evgenyrodionov commented on product-page.html
> +                  <a class="footer-navigation-link" href="#">Contact Us</a>
в нав бы обернуть

2017-08-05 15:36 UTC, evgenyrodionov commented on product-page.html
> +                  <h3 class="footer-navigation-title">CUSTOMER SERVICE</h3>
h3 слишком высокий заголовок, перечитай телеграф про их иерархию

2017-08-05 17:56 UTC, imevro approved these changes

2017-08-05 18:58 UTC, shaste commented
Вешаю ПР, чтобы ты не потерял меня на пути во второй этап

2017-08-06 07:39 UTC, merged

2017-08-06 07:39 UTC, evgenyrodionov commented
Переключаешься в мастер, делаешь гит пулл ориджин мастер --ребейз, делаешь бранчи от этого нового мастера