Product page React
shaste/fake-burrberry-frontend pull request #2
Opened 2017-08-10 20:57 UTC by shaste

2017-08-10 22:43 UTC, imevro requested changes

2017-08-10 22:43 UTC, evgenyrodionov commented on public/manifest.json
> +  "name": "fake-burberry-frontend",
странный нейм

2017-08-10 22:43 UTC, evgenyrodionov commented on src/App.js
> +import Header from "./Header.jsx";
опусти .jsx

2017-08-10 22:43 UTC, evgenyrodionov commented on src/App.js
> +class App extends Component {
зачем класс

2017-08-10 22:43 UTC, evgenyrodionov commented on src/Common/Divider.jsx
> +const Divider = styled.hr`
делай сразу тут экспорт дефолт

2017-08-10 22:43 UTC, evgenyrodionov commented on src/Product/ButtonText.jsx
> +  background-color: Transparent;
почему с большой буквы лол

2017-08-10 22:43 UTC, evgenyrodionov commented on src/Product/ButtonText.jsx
> +  background-color: Transparent;
уважительно и по-русски

2017-08-10 22:43 UTC, evgenyrodionov commented on src/Product/ColorButton.jsx
> +export default function(props) {
а что мешает сразу ColorButton экспортнуть и использовать? зачем эта прокладка?

2017-08-10 22:43 UTC, evgenyrodionov commented on src/Product/Title.jsx
> +    {
что за блок в блоке

2017-08-11 11:26 UTC, imevro requested changes

2017-08-11 11:26 UTC, evgenyrodionov commented on src/Common/Divider.jsx
> +export const Divider = styled.hr`
да можно и дефолт

2017-08-11 11:26 UTC, evgenyrodionov commented on src/Product/Details.jsx
> +import {ButtonText} from "./ButtonText";
да, реал, сделай дефолт

2017-08-11 11:26 UTC, evgenyrodionov commented on src/Product/Details.jsx
> +      <Price price="100 000" id="39428531" />
цену числом + react-intl для форматирования валюты

2017-08-11 11:26 UTC, evgenyrodionov commented on src/Product/RelevantLinks.jsx
> +import {SectionTitle} from "../Common/SectionTitle.jsx";
опять .jsx

2017-08-11 19:23 UTC, imevro requested changes

2017-08-11 19:23 UTC, evgenyrodionov commented on src/Product/Details.jsx
> +        price="100000"
числом, не строкой

2017-08-12 11:56 UTC, imevro requested changes

2017-08-12 11:56 UTC, evgenyrodionov commented on src/Product/Description.jsx
> +              <div className="col-lg-4">
что за отступы лишние, поставь преттир

2017-08-12 11:56 UTC, evgenyrodionov commented on src/Product/Details.jsx
> +        <Price
тут вообще не нужен реакт-респонсив, выкинь

2017-08-12 17:53 UTC, evgenyrodionov commented on src/Common/Breakpoints.jsx
>  export const XsMd = ({ children }) => <Responsive minWidth={0} maxWidth={991}>{children}</Responsive>;
А зачем этот компонент если ты можешь компоненты нестить?

```<Xs><Md>x</Md></Xs>```

2017-08-12 19:08 UTC, shaste commented
Как я писал в чате, вложенные компоненты респонсива не срабатывают. Поэтому вешаю опять ПР

2017-08-12 21:12 UTC, imevro approved these changes
вроде ок

2017-08-13 11:00 UTC, merged